# 1. Node image
FROM node:20-alpine

# 2. Work directory
WORKDIR /usr/src/app

# 3. Install dependencies
COPY package*.json ./
RUN npm install

# 4. Copy code
COPY . .

# 5. Vite/React default port
EXPOSE 5173

# 6. Start development server
CMD ["npm", "run", "dev", "--", "--host"]