version: '3.8'

services:
  # Database Service
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reading_tracker_db
    ports:
      - "5432:5432"

  # Backend Service
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/reading_tracker_db

# Frontend Service
  frontend:
    build: ./Frontend
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend